### ISSUE TITLE
Créer le thème

### ISSUE THREAD

**Issue by Llianae** [LoicWalter/CESI-Eats#49]

**Comment by Llianae** [comment]
Le thème du client et du restaurant est fait normalement
Si vous voyez un oublie dites le
Lucas veut faire le thème pour le livreur, donc il ne faut pas merge le ticket tant qu'il ne l'a pas fait
@Artros68 Je te laisse envoyer un message ici quand ce sera fait

**Comment by Artros68** [comment]
@Llianae Tu vois le message ?

**Comment by Artros68** [comment]
@Llianae Tu vois le message ?

**Comment by Llianae** [comment]
@Artros68 oui

**Comment by Llianae** [comment]
@Artros68 t'as push ?
